name: CI

on: [push, pull_request]

jobs:
  check:
    name: Check
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        action: [build, lint, test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: npm run ${{ matrix.action }}
  release:
    name: Release
    needs: check
    if: github.event_name	== 'push'
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org
      - name: Determine Release Information
        id: release-info
        uses: ./.github/actions/release-info
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Set Version
        run: npm version ${{ steps.release-info.outputs.version }} --git-tag-version=false
      - name: Publish
        run: |
          args=( --tag="${{ steps.release-info.outputs.distTag }}" )
          if [ -z "${NODE_AUTH_TOKEN}" ]; then
            echo "Auth token not found. Executing dry run publish."
            args+=( --dry-run )
          fi;
          mv dist/core core;
          npm publish "${args[@]}"
          if [ -z "${NODE_AUTH_TOKEN}" ]; then
            echo "Dry run publish complete."
          fi;
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
